### ISSUE TITLE
Add new Partners to collaboration wall

### ISSUE THREAD

**Issue by TidosDK** [Aaveq-Robotics/Aaveq-Robotics.github.io#2]
We are missing a few partners we collaborate with, on the collaboration wall. These should be added.

**Comment by PositiveBeat** [comment]
We need the funding logos, should that be a different section than partners, and perhaps a new issue also?

**Comment by PositiveBeat** [comment]
Talked with Ernst, and we can't call companies that have funded us for partners. It should be a different section, perhaps on the bottom of the website, that says something along the lines of "Thanks for the support" ("Tak for støtten" in a formal way).

**Comment by TidosDK** [comment]
I believe we will remove the partners section and only have the funding section.
I will close this issue.

**Comment by TidosDK** [comment]
Correct close*
